{% set name = "neper" %}
{% set version = "4.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rquey/neper/archive/v{{ version }}.tar.gz
  sha256: 957c40360373158f0d5628ff896afc77cb261a0e217d85008e8a262bc164ce35

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - cmake
    - libblas
    - llvm-openmp  # [osx]
    - gsl
    - scotch
    - nlopt
    - openmp
  run:
    - gsl
    - scotch
    - nlopt
    - openmp
    - gmsh

test:
  commands:
    - neper --help

about:
  home: http://neper.info/
  license: GPL-3
  license_family: GPL
  license_file:
    - COPYING
    - CREDITS
  summary: Neper is a software package for polycrystal generation and meshing.
  doc_url: https://rquey.github.io/neper/docs/neper.pdf
  dev_url: https://github.com/rquey/neper

extra:
  recipe-maintainers:
    - npavlovikj
